### ISSUE TITLE
Parsing time not adjusting for pm.

### ISSUE THREAD

**Issue by jsearles** [globalizejs/globalize#740] opened 2017-06-05 14:08 UTC
I am attempting to parse a PM time using "en-US" as the locale. The value i'm attempting to parse is "2:12:34 pm". I am using a skeleton of "jms". The time parses, but does not adjust the 12 hours for PM. When i step through the code, this is the portion that looks like it should be accounting for PM:

```js
	if ( hour12 && amPm === "pm" ) {
		date.setHours( date.getHours() + 12 );
	}
```

However "amPm" is equal to "pm-alt-variant" at this point, so the time is not adjusted.

I am using version "1.3.0-rc.0".

**Comment by jrsearles** [comment] 2017-06-12 17:41
OK, doing some more debugging i've determined this is caused by the fact that the "pm" indicator is lower case in the string. This is matching with "pm-alt-variant" in CLDR. Globalize should likely be checking for this value in the above block as well.

**Comment by rxaviers** [comment] 2017-06-12 18:10
Closing in favor of #544 (PR #546)

**Closed** 2017-06-12 18:10 UTC
